// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parks.Models;

namespace Parks.Migrations
{
    [DbContext(typeof(ParksContext))]
    [Migration("20220401214457_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Parks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30) CHARACTER SET utf8mb4");

                    b.Property<bool>("Hiking")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2) CHARACTER SET utf8mb4");

                    b.Property<bool>("Swimming")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            City = "Post Falls",
                            Hiking = true,
                            Name = "Q’emiln Park",
                            Size = 508,
                            State = "ID",
                            Swimming = true
                        },
                        new
                        {
                            ParkId = 2,
                            City = "Spokane",
                            Hiking = true,
                            Name = "People's Park",
                            Size = 258,
                            State = "WA",
                            Swimming = true
                        },
                        new
                        {
                            ParkId = 3,
                            City = "Gresham",
                            Hiking = true,
                            Name = "Oneonta Park",
                            Size = 106,
                            State = "OR",
                            Swimming = false
                        },
                        new
                        {
                            ParkId = 4,
                            City = "Springfield",
                            Hiking = true,
                            Name = "Blair Park",
                            Size = 766,
                            State = "MA",
                            Swimming = false
                        },
                        new
                        {
                            ParkId = 5,
                            City = "Newport",
                            Hiking = true,
                            Name = "Agate Beach",
                            Size = 1405,
                            State = "OR",
                            Swimming = true
                        },
                        new
                        {
                            ParkId = 6,
                            City = "Gresham",
                            Hiking = true,
                            Name = "Ainsworth",
                            Size = 1405,
                            State = "OR",
                            Swimming = false
                        },
                        new
                        {
                            ParkId = 7,
                            City = "Triangle Lake",
                            Hiking = true,
                            Name = "Alderwood Wayside",
                            Size = 895,
                            State = "OR",
                            Swimming = true
                        },
                        new
                        {
                            ParkId = 8,
                            City = "Hood River",
                            Hiking = true,
                            Name = "Angel's Rest",
                            Size = 2719,
                            State = "OR",
                            Swimming = true
                        },
                        new
                        {
                            ParkId = 9,
                            City = "Portland",
                            Hiking = true,
                            Name = "Banks Vernonia Trail",
                            Size = 2719,
                            State = "OR",
                            Swimming = false
                        },
                        new
                        {
                            ParkId = 10,
                            City = "Spokane",
                            Hiking = false,
                            Name = "Riverfront Park",
                            Size = 595,
                            State = "WA",
                            Swimming = false
                        },
                        new
                        {
                            ParkId = 11,
                            City = "Pendleton",
                            Hiking = true,
                            Name = "Battle Mountain",
                            Size = 367,
                            State = "OR",
                            Swimming = false
                        },
                        new
                        {
                            ParkId = 12,
                            City = "Portland",
                            Hiking = true,
                            Name = "Bald Peak",
                            Size = 246,
                            State = "OR",
                            Swimming = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
